### ISSUE TITLE
Gif version in demo doesnt work

### ISSUE THREAD

**Issue by robmausser** [DavidAnson/live-photo-web#1]
In the demo you provide, you say gif version "works everywhere" but it does not.

It doesnt on chrome. Im running chrome version 76 and hovering the mouse over the gif does nothing.

Mp4 works though

**Comment by DavidAnson** [comment]
Testing in Chrome 76.0.3809.100 on Windows 10, both GIF and MP4 still work. The GIF file is pretty large, so you may need to wait a bit for it to download on a slow connection. If that doesn't help, please have a look at the Console/Network tabs in F12 Dev Tools for a hint about why it's failing for you. (Possibly an ad/content blocker or firewall?) You might also try loading the demo in a Private/Incognito window - that usually bypasses problematic browser extensions.

**Comment by DavidAnson** [comment]
FYI, while looking at the console in Chrome, I noticed a deprecation warning for v0 custom element support in Chrome M80, so I've updated the sample to use the v1 spec: https://github.com/DavidAnson/live-photo-web/commit/19b98c5032446661640dd95525e14d618d3f287c. Both samples continue to work in Chrome 76, but `live-photo-image` no longer works in Safari due to a missing implementation there.

Also FYI, please try clicking in the page before hovering the mouse - in some cases Chrome wants user interaction before allowing the sample to interact with the DOM.

**Comment by robmausser** [comment]
Unfortunately even after waiting over a minute (I have gigabit internet though) and using incognito mode in a fresh installation of chrome will all extensions turned off, the gif version does not work

https://photos.app.goo.gl/bcVFy5Ztmbabtm6v6

**Comment by robmausser** [comment]
Got it too work, it just took a loooong time to load while hovering. Cheers
